const dropZone = document.getElementById("dropZone")
const fileInput = document.getElementById("fileInput")
const terminal = document.getElementById("terminal")

dropZone.addEventListener("dragover", e => {

e.preventDefault()
dropZone.style.borderColor="#00ff9c"

})

dropZone.addEventListener("drop", e => {

e.preventDefault()

fileInput.files = e.dataTransfer.files

})

function logTerminal(text){

terminal.innerHTML += text + "<br>"
terminal.scrollTop = terminal.scrollHeight

}

async function scanFile(){

const result = document.getElementById("result")

if(!fileInput.files.length){

result.innerHTML="Upload file first"
return

}

const file = fileInput.files[0]

terminal.innerHTML=""

logTerminal("Initializing FileSentinel...")
logTerminal("Generating SHA256 hash...")
logTerminal("Connecting to VirusTotal API...")

try{

const formData = new FormData()

formData.append("file",file)

const upload = await fetch(

"https://www.virustotal.com/api/v3/files",

{

method:"POST",

headers:{

"x-apikey":API_KEY

},

body:formData

}

)

const uploadData = await upload.json()

logTerminal("File uploaded successfully")

const id = uploadData.data.id

logTerminal("Analyzing malware signatures...")

await new Promise(r=>setTimeout(r,5000))

const analysis = await fetch(

`https://www.virustotal.com/api/v3/analyses/${id}`,

{

headers:{

"x-apikey":API_KEY

}

}

)

const data = await analysis.json()

const stats = data.data.attributes.stats

const malicious = stats.malicious
const harmless = stats.harmless
const suspicious = stats.suspicious

let status="SAFE"
let cls="safe"

if(malicious>0){

status="MALWARE DETECTED"
cls="danger"

}

logTerminal("Scan complete.")

result.innerHTML=

`

<h3>Scan Report</h3>

<p>File: ${file.name}</p>

<p>Harmless: ${harmless}</p>
<p>Suspicious: ${suspicious}</p>
<p>Malicious: ${malicious}</p>

<h2 class="${cls}">${status}</h2>

`

}

catch{

result.innerHTML="API Error or rate limit exceeded"

}

}

lastScan = {

    fileName: file.name,
    harmless: harmless,
    suspicious: suspicious,
    malicious: malicious,
    status: status
    
    }
    
    document.getElementById("downloadReport").style.display="inline-block"

    function downloadPDF(){

        const { jsPDF } = window.jspdf
        
        const doc = new jsPDF()
        
        doc.setFontSize(22)
        doc.text("FileSentinel Malware Report",20,20)
        
        doc.setFontSize(12)
        
        doc.text("File Name: " + lastScan.fileName,20,40)
        
        doc.text("Harmless: " + lastScan.harmless,20,60)
        doc.text("Suspicious: " + lastScan.suspicious,20,70)
        doc.text("Malicious: " + lastScan.malicious,20,80)
        
        doc.text("Threat Status: " + lastScan.status,20,100)
        
        doc.text("Generated by FileSentinel",20,130)
        
        doc.save("malware_report.pdf")
        
        }
        

let lastScan = {
    fileName:"",
    harmless:0,
    suspicious:0,
    malicious:0,
    status:""
    }
    